### ISSUE TITLE
Failing on Spark 3.1.2

### ISSUE THREAD

**Issue by franji-pagaya** [nielsbasjes/splittablegzip#33]
Hi,
I get an exception trying to start session with spark.jars.packages='nl.basjes.hadoop:splittablegzip:1.3'
java.lang.ClassNotFoundException: java.lang.NoClassDefFoundError: Could not initialize class org.slf4j.LoggerFactory when creating Hive client using classpath

Anyone with experience in running on Spark 3+?

**Comment by nielsbasjes** [comment]
I personally don't use Spark. The error seems to indicate log4j2 is missing on the classpath. Have you tried adding these jars to your installation?
If you have a minimal reproduction of this problem that I can run locally (docker) I can have a look if I can help.

Niels

**Comment by nielsbasjes** [comment]
No feedback since a few months so I assume it has been fixed.

**Comment by franji-pagaya** [comment]
Yes, sorry for not replying - the notifications got filtered. 
We used another approach (splitting the files beforehand outside of Spark).
Thanks you and sorry for the trouble.
