### ISSUE TITLE
How to avoid executors on same node/ tasks on same executor read the large gz file parallelly 

### ISSUE THREAD

**Issue by MyqueWooMiddo** [nielsbasjes/splittablegzip#64]
The parallelly duplicated read will make the network in high throughput.
I think executors on same node or  tasks on same executor should share the content of file , but make locality.wait longer could not solve the problem .
What can I do?

**Comment by nielsbasjes** [comment]
As mentioned in the documentation https://github.com/nielsbasjes/splittablegzip#tuning-for-optimal-performance-and-scalability

I recommend tweaking things like blocksize and replication to reduce the network impact of this.

**Comment by MyqueWooMiddo** [comment]
> 

I'll try the recommendation
